spring:
  servlet:
    multipart:
      maxFileSize: 5000MB
      maxRequestSize: 5000MB
  application:
    name: eureka-client-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mancity?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: ssafy
      password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    data:
      web:
        pageable:
          one-indexed-parameters: true

server:
  port: 8081
  servlet:
    contextPath: /
  servlet.encoding:
    charset: UTF-8
    enabled: true
    force: true
  java:
    options:
      - "-Dfile.encoding=UTF-8"
      - "-Dconsole.encoding=UTF-8"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka #Eureka Server ??
  instance:
    hostname: localhost

build:
  date: '@build.date@'
